---
# tasks file for template
- name: update all software (CentOS)
  yum:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_distribution == "CentOS"
  tags:
    - skip_ansible_lint

- name: update all software (Fedora)
  dnf:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_distribution == "Fedora"
  tags:
    - skip_ansible_lint

- name: update all software (openSUSE)
  zypper:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_distribution == "openSUSE Leap"
  tags:
    - skip_ansible_lint

- name: update all software (Debian/Ubuntu)
  apt:
    update_cache: yes
    upgrade: dist
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_distribution in [ "Debian", "Ubuntu" ]

- name: flush handlers
  meta: flush_handlers
