---
# tasks file for update
- name: update all software (yum)
  yum:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_pkg_mgr == "yum"
  tags:
    - skip_ansible_lint
  register: ansibleroleupdate

- name: update all software (dnf)
  dnf:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_pkg_mgr == "dnf"
  tags:
    - skip_ansible_lint
  register: ansibleroleupdate

- name: update all software (zypper)
  zypper:
    name: "*"
    state: latest
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_pkg_mgr == "zypper"
  tags:
    - skip_ansible_lint
  register: ansibleroleupdate

- name: update all software (apt)
  apt:
    update_cache: yes
    upgrade: dist
  notify:
    - reboot
    - wait for the machine to be down
    - wait for the machine to be up
  when:
    - ansible_pkg_mgr == "apt"
  register: ansibleroleupdate

- name: apt autoremove (apt)
  apt:
    autoremove: "{{ update_autoremove }}"
  when:
    - ansible_pkg_mgr == "apt"
    - update_autoremove == "yes"

- name: flush handlers
  meta: flush_handlers
