---
# handlers file for update
- name: reboot
  shell: (sleep "{{ update_reboot_delay }}" && shutdown -r now "ansible-role-update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  # changed_when: no
  when:
    - ansible_virtualization_type != "docker"
    - update_reboot
  notify:
    - wait for the machine to be down

- name: wait for the machine to be down
  local_action: wait_for
  args:
    host: {{ ansible_ssh_host }}
    port: {{ ansible_ssh_port }}
    state: stopped

# - name: wait for the machine to be down
#   wait_for_connection:
#     connect_timeout: "{{ update_down_connect_timeout }}"
#     sleep: "{{ update_down_sleep }}"
#     timeout: "{{ update_down_timeout }}"
#   register: connection
#   until: connection is failed
#   retries: "{{ update_down_retries }}"
#   failed_when:
#     - connection is success
#   changed_when:
#     - connection is failed
#   when:
#     - ansible_virtualization_type != "docker"
#   notify:
#     - wait for the machine to be up

- name: wait for the machine to be up
  wait_for_connection:
