---
# handlers file for update
- name: reboot
  shell: (sleep 3 && shutdown -r now "update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  notify: wait for the machine to be up
  when:
    - ansible_virtualization_type != "docker"

- name: wait for the machine to be down
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: "{{ ansible_port }}"
    state: stopped
  notify: wait for the machine to be up

- name: wait for the machine to be up
  become: no
  delegate_to: localhost
  wait_for_connection:
    delay: "{{ update_delay }}"
