---
# handlers file for update
- name: reboot
  shell: (sleep 10 && shutdown -r now "ansible-role-update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  changed_when: no
  when:
    - ansible_virtualization_type != "docker"

- name: wait for the machine to be down
  wait_for_connection:
  register: connection
  until: connection | failed
  retries: 10
  failed_when:
    - connection | success
  when:
    - ansible_virtualization_type != "docker"

- name: wait for the machine to be up
  wait_for_connection:
