---
# handlers file for update
- name: reboot
  shell: (sleep "{{ update_reboot_delay }}" && shutdown -r now "ansible-role-update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  changed_when: no
  when:
    - ansible_virtualization_type != "docker"

- name: wait for the machine to be down
  wait_for_connection:
  register: connection
  until: connection | failed
  retries: "{{ update_down_retries }}"
  delay: "{{ update_down_delay }}"
  failed_when:
    - connection | success
  when:
    - ansible_virtualization_type != "docker"

- name: wait for the machine to be up
  wait_for_connection:
