---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-update
      update_autoremove: yes

  tasks:
    - name: test connection
      ping:
