---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no
  strategy: free

  roles:
    - role: ansible-role-update
      update_autoremove: yes

  tasks:
    - name: test connection
      ping:
