---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-update
      update_autoremove: true

  tasks:
    - name: test connection
      ping:
